wandb_version: 1

out_dir:
  desc: null
  value: results
dataloader:
  desc: null
  value:
    data_path: ''
    radius: 30
dataset:
  desc: null
  value:
    prediction_task: node
    num_classes: 4
gnn:
  desc: null
  value:
    gnn_type: GCN
    num_layers: 2
    num_features: 20
    hidden_dim: 16
    embed_dim: 8
transformer:
  desc: null
  value:
    d_model: 128
    n_heads: 4
    dim_feedforward: 512
    dropout: 0.3
    num_layers: 4
    activation_func: relu
    num_encoder_layers: 4
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710698738.624478
    t:
      1:
      - 1
      - 54
      - 55
      - 77
      2:
      - 1
      - 54
      - 55
      - 77
      3:
      - 2
      - 16
      - 23
      4: 3.9.18
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
